import { expect, it, beforeEach } from "vitest";
import { render, screen, within, waitFor } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { CalculatorApp } from "@/features/calculator/CalculatorApp";
import { PresetStatWindow } from "@/features/calculator/components/PresetStatWindow";
import { createDefaultInput } from "@/features/calculator/domain/defaults";
import { calculateDamageResult } from "@/features/calculator/domain/calculate";
import { serializeSetup, STORAGE_KEY } from "@/features/calculator/storage";
beforeEach(()=>localStorage.clear());
it("follows the selected weapon and combat target, with fixed pure stats and live buffs",async()=>{
  const input=createDefaultInput("corsair");input.equipment.projectile!.attackFlat="0";Object.assign(input.character,{level:"200",pureMain:"1000",pureSub:"22",guildBossPercent:"5",guildAttackFlat:"0",guildIgnorePercent:"0"});
  Object.assign(input.equipment.necklace!,{mainFlat:"100",subFlat:"20",mainPercent:"100",subPercent:"80",requiredLevel:"0",requiredSub:"0"});
  Object.assign(input.equipment.weapon!,{attackFlat:"100",totalDamagePercent:"10",bossDamagePercent:"20",requiredLevel:"0",requiredSub:"0"});
  input.weaponPresets={active:"boss",entries:{hunting:{weapon:{...input.equipment.weapon!},monsterDefense:"0"},chaos:{weapon:{...input.equipment.weapon!,attackFlat:"200",mainFlat:"10"},monsterDefense:"80"}}};
  localStorage.setItem(STORAGE_KEY,serializeSetup(input));render(<CalculatorApp/>);
  const sheet=await screen.findByRole("region",{name:"적용 후 스탯창"});
  await waitFor(()=>expect(within(sheet).getByLabelText("시뮬레이션 DEX 순수 및 추가 스탯")).toHaveTextContent("순수 1,000 + 추가 1,306"));
  expect(within(sheet).getByLabelText("시뮬레이션 STR 순수 및 추가 스탯")).toHaveTextContent("순수 22 + 추가 61");
  expect(within(sheet).getByLabelText("시뮬레이션 스탯 공격력 결과")).toHaveTextContent("8,552");
  expect(within(sheet).getByLabelText("시뮬레이션 환산 공격력 결과")).toHaveTextContent("11,545");
  const efficiency=screen.getByRole("region",{name:"적용 후 옵션 효율"});
  expect(within(efficiency).getByLabelText("적용 후 보공 +1% 주스탯 환산")).not.toHaveTextContent(/^0 DEX$/);
  const user=userEvent.setup();await user.click(screen.getByRole("button",{name:"사냥용 프리셋 선택"}));
  expect(sheet).toHaveTextContent("사냥용");expect(within(sheet).getByLabelText("시뮬레이션 환산 공격력 결과")).toHaveTextContent("9,407");
  expect(within(efficiency).getByLabelText("적용 후 보공 +1% 주스탯 환산")).toHaveTextContent("0 DEX");
  await user.click(screen.getByRole("button",{name:"카오스 보스용 프리셋 선택"}));
  expect(sheet).toHaveTextContent("카오스 보스용");expect(within(sheet).getByLabelText("시뮬레이션 DEX 순수 및 추가 스탯")).toHaveTextContent("순수 1,000 + 추가 1,326");
  const before=within(sheet).getByLabelText("시뮬레이션 스탯 공격력 결과").textContent;
  const efficiencyBefore=efficiency.textContent;
  await user.click(screen.getByRole("button",{name:"핑크빈 +35"}));
  expect(efficiency.textContent).not.toBe(efficiencyBefore);
  expect(within(sheet).getByLabelText("시뮬레이션 스탯 공격력 결과").textContent).not.toBe(before);
  expect(within(sheet).getByLabelText("시뮬레이션 현재 적용 버프")).toHaveTextContent("현재 선택 버프 유지");
  expect(within(sheet).getByLabelText("시뮬레이션 DEX 순수 및 추가 스탯")).toHaveTextContent("순수 1,000");
});
it("uses the same critical contributions as the actual damage formula",()=>{
  const input=createDefaultInput("marksman");Object.assign(input.character,{criticalRate:"5",sharpEyes:"sharp_30"});
  const result=calculateDamageResult(input);
  expect(result.criticalStats).toEqual({baseRate:40,equipmentRate:0,extraRate:5,buffRate:15,baseDamage:100,buffDamage:140,totalDamage:240,damageInterpretation:"additional"});
  render(<PresetStatWindow input={input} result={result} buffSummary="공격력 버프 없음"/>);
  expect(screen.getByText("60%")).toBeInTheDocument();expect(screen.getByText("240%")).toBeInTheDocument();
  expect(screen.getByText("×1.533")).toBeInTheDocument();expect(screen.getByText("기본 40 + 장비 0 + 기타 5 + 버프 15")).toBeInTheDocument();
  expect(screen.getByText("순수 스탯 추정")).toBeInTheDocument();
});
it("shows Night Lord's actual main/sub axes and STR without inventing a base split",()=>{
  const input=createDefaultInput("night_lord");input.character.nightLordStrStat="44";
  render(<PresetStatWindow input={input} result={calculateDamageResult(input)} buffSummary="공격력 버프 없음"/>);
  expect(screen.getByLabelText("LUK 순수 및 추가 스탯")).toBeInTheDocument();
  expect(screen.getByLabelText("DEX 순수 및 추가 스탯")).toBeInTheDocument();
  expect(screen.queryByLabelText("STR 순수 및 추가 스탯")).not.toBeInTheDocument();
  expect(screen.getByText("44")).toBeInTheDocument();
});
